# Generated by Django 4.1 on 2022-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
