# Generated by Django 4.1 on 2022-08-25 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
