# Generated by Django 4.1 on 2022-08-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
