# Generated by Django 4.1 on 2022-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='parentId',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
