# Generated by Django 4.1 on 2022-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_unit_date_alter_unit_parent_alter_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
